#!/bin/bash

HOST=
DB=
COLLECTION=
USER=
PW=

DUMP=rawOutput.json
OUTPUT=output.xls

echo -n "Exporting data from MongoLab..."
mongoexport -h $HOST -d $DB -c $COLLECTION -u $USER -p $PW -o $DUMP >/dev/null
echo "Done!"

coffee mongo2Excel.coffee $DUMP $OUTPUT

